version: '2.2'
services:
  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_DB: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_USER: flow
    ports:
      - 5435:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d airflow -U flow" ]
      interval: 30s
      timeout: 30s
      retries: 3
  webserver:
    container_name: webserver_airflow
    build:
      context: .
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://flow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8000
      - AIRFLOW__CLI__ENDPOINT_URL=http://localhost:8000
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8000
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/usr/local/airflow/logs
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False
    volumes:
      - ./dags:/usr/local/airflow/dags:rw
      - ./plugins:/usr/local/airflow/plugins:rw
    ports:
      - "1234:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["webserver"]
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 5
  scheduler:
    container_name: scheduler_airflow
    build:
      context: .
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://flow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8000
      - AIRFLOW__CLI__ENDPOINT_URL=http://localhost:8000
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8000
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/usr/local/airflow/logs
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False
    volumes:
      - ./dags:/usr/local/airflow/dags:rw
      - ./plugins:/usr/local/airflow/plugins:rw
    depends_on:
      postgres:
        condition: service_healthy
      webserver:
        condition: service_healthy
    command: ["scheduler"]
